/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as OMneRouteImport } from './routes/o-mne'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as IndexRouteImport } from './routes/index'

const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const OMneRoute = OMneRouteImport.update({
  id: '/o-mne',
  path: '/o-mne',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/reference': typeof ReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/reference': typeof ReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/kontakt': typeof KontaktRoute
  '/o-mne': typeof OMneRoute
  '/reference': typeof ReferenceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galerie'
    | '/kontakt'
    | '/o-mne'
    | '/reference'
    | '/sitemap.xml'
    | '/sluzby'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galerie'
    | '/kontakt'
    | '/o-mne'
    | '/reference'
    | '/sitemap.xml'
    | '/sluzby'
  id:
    | '__root__'
    | '/'
    | '/galerie'
    | '/kontakt'
    | '/o-mne'
    | '/reference'
    | '/sitemap.xml'
    | '/sluzby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalerieRoute: typeof GalerieRoute
  KontaktRoute: typeof KontaktRoute
  OMneRoute: typeof OMneRoute
  ReferenceRoute: typeof ReferenceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SluzbyRoute: typeof SluzbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mne': {
      id: '/o-mne'
      path: '/o-mne'
      fullPath: '/o-mne'
      preLoaderRoute: typeof OMneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalerieRoute: GalerieRoute,
  KontaktRoute: KontaktRoute,
  OMneRoute: OMneRoute,
  ReferenceRoute: ReferenceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SluzbyRoute: SluzbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
